import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "1.0.0/api-reference",
      label: "API Reference",
      className: "api-method intro",
    },
    {
      type: "doc",
      id: "1.0.0/parameters",
      label: "API Parameters",
      className: "api-method intro",
    },
    {
      type: "doc",
      id: "1.0.0/completion",
      label: "Completion",
      className: "api-method post",
    },
    {
      type: "doc",
      id: "1.0.0/chat-completion",
      label: "Chat Completion",
      className: "api-method post",
    },
    {
      type: "doc",
      id: "1.0.0/messages",
      label: "Messages",
      className: "api-method post",
    },
    {
      type: "doc",
      id: "1.0.0/list-available-models",
      label: "List available models",
      className: "api-method get",
    },
    {
      type: "category",
      label: "Jev",
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "1.0.0/systemone",
          label: "Evaluate (System One)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Realtime",
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "1.0.0/realtime",
          label: "Realtime session",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "1.0.0/realtime-client-secrets",
          label: "Create realtime client secret",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/realtime-calls",
          label: "Create realtime call",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Video Generation",
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "1.0.0/create-video",
          label: "Submit a video generation request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/get-video",
          label: "Poll video generation status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "1.0.0/get-video-content",
          label: "Download generated video content",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "1.0.0/list-video-models",
          label: "List all video generation models",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Music",
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "1.0.0/list-music-models",
          label: "List music models",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "1.0.0/compose-music",
          label: "Compose music",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/stream-music",
          label: "Stream music",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/compose-detailed-music",
          label: "Compose music with details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/compose-detailed-stream-music",
          label: "Stream music with details",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/create-composition-plan",
          label: "Create composition plan",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/upload-music",
          label: "Upload music",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/separate-stems",
          label: "Separate stems",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/video-to-music",
          label: "Video to music",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/list-music-finetunes",
          label: "List music finetunes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "1.0.0/create-music-finetune",
          label: "Create music finetune",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/get-music-finetune",
          label: "Get music finetune",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "1.0.0/update-music-finetune",
          label: "Update music finetune",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "1.0.0/delete-music-finetune",
          label: "Delete music finetune",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Text to Speech",
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "1.0.0/list-tts-models",
          label: "List text-to-speech models",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "1.0.0/convert-speech",
          label: "Create speech",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/stream-speech",
          label: "Stream speech",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/convert-speech-with-timestamps",
          label: "Create speech with timing",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/stream-speech-with-timestamps",
          label: "Stream speech with timing",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/tts-stream-input",
          label: "Text-to-speech WebSocket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "1.0.0/tts-multi-stream-input",
          label: "Multi-context TTS WebSocket",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Speech to Text",
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "1.0.0/list-stt-models",
          label: "List speech-to-text models",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "1.0.0/convert-speech-to-text",
          label: "Create transcript",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "1.0.0/get-transcript",
          label: "Get transcript",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "1.0.0/delete-transcript",
          label: "Delete transcript",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "1.0.0/stt-realtime",
          label: "Realtime speech-to-text",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Voices",
      collapsed: true,
      items: [
        { type: "doc", id: "1.0.0/list-voices", label: "List voices", className: "api-method get" },
        { type: "doc", id: "1.0.0/search-voices", label: "Search voices", className: "api-method get" },
        { type: "doc", id: "1.0.0/get-voice", label: "Get voice", className: "api-method get" },
        { type: "doc", id: "1.0.0/edit-voice", label: "Edit voice", className: "api-method post" },
        { type: "doc", id: "1.0.0/delete-voice", label: "Delete voice", className: "api-method delete" },
        { type: "doc", id: "1.0.0/create-ivc-voice", label: "Create instant voice clone", className: "api-method post" },
        { type: "doc", id: "1.0.0/add-shared-voice", label: "Add shared voice", className: "api-method post" },
        { type: "doc", id: "1.0.0/find-similar-voices", label: "Find similar voices", className: "api-method post" },
        { type: "doc", id: "1.0.0/list-shared-voices", label: "List shared voices", className: "api-method get" },
        { type: "doc", id: "1.0.0/get-voice-accents", label: "Get voice accents", className: "api-method get" },
        { type: "doc", id: "1.0.0/get-default-voice-settings", label: "Get default voice settings", className: "api-method get" },
        { type: "doc", id: "1.0.0/get-voice-settings", label: "Get voice settings", className: "api-method get" },
        { type: "doc", id: "1.0.0/edit-voice-settings", label: "Edit voice settings", className: "api-method post" },
        { type: "doc", id: "1.0.0/get-voice-sample-audio", label: "Get voice sample audio", className: "api-method get" },
        { type: "doc", id: "1.0.0/delete-voice-sample", label: "Delete voice sample", className: "api-method delete" },
        { type: "doc", id: "1.0.0/replicate-voice", label: "Replicate voice", className: "api-method post" },
        { type: "doc", id: "1.0.0/create-pvc-voice", label: "Create PVC voice", className: "api-method post" },
        { type: "doc", id: "1.0.0/update-pvc-voice", label: "Update PVC voice", className: "api-method post" },
        { type: "doc", id: "1.0.0/train-pvc-voice", label: "Train PVC voice", className: "api-method post" },
        { type: "doc", id: "1.0.0/create-pvc-samples", label: "Create PVC samples", className: "api-method post" },
        { type: "doc", id: "1.0.0/update-pvc-sample", label: "Update PVC sample", className: "api-method post" },
        { type: "doc", id: "1.0.0/delete-pvc-sample", label: "Delete PVC sample", className: "api-method delete" },
        { type: "doc", id: "1.0.0/get-pvc-sample-audio", label: "Get PVC sample audio", className: "api-method get" },
        { type: "doc", id: "1.0.0/get-pvc-sample-waveform", label: "Get PVC sample waveform", className: "api-method get" },
        { type: "doc", id: "1.0.0/get-pvc-speakers", label: "Get PVC speakers", className: "api-method get" },
        { type: "doc", id: "1.0.0/get-pvc-speaker-audio", label: "Get PVC speaker audio", className: "api-method get" },
        { type: "doc", id: "1.0.0/separate-pvc-speakers", label: "Separate PVC speakers", className: "api-method post" },
        { type: "doc", id: "1.0.0/request-pvc-verification", label: "Request PVC verification", className: "api-method post" },
        { type: "doc", id: "1.0.0/get-pvc-captcha", label: "Get PVC captcha", className: "api-method get" },
        { type: "doc", id: "1.0.0/verify-pvc-captcha", label: "Verify PVC captcha", className: "api-method post" },
      ],
    },
    {
      type: "category",
      label: "Voice Changer",
      collapsed: true,
      items: [
        { type: "doc", id: "1.0.0/list-sts-models", label: "List Voice Changer models", className: "api-method get" },
        { type: "doc", id: "1.0.0/convert-speech-to-speech", label: "Convert speech to speech", className: "api-method post" },
        { type: "doc", id: "1.0.0/stream-speech-to-speech", label: "Stream speech to speech", className: "api-method post" },
      ],
    },
    {
      type: "category",
      label: "Voice Isolator",
      collapsed: true,
      items: [
        { type: "doc", id: "1.0.0/list-isolation-models", label: "List Voice Isolator models", className: "api-method get" },
        { type: "doc", id: "1.0.0/isolate-audio", label: "Isolate audio", className: "api-method post" },
        { type: "doc", id: "1.0.0/stream-isolate-audio", label: "Stream isolated audio", className: "api-method post" },
        { type: "doc", id: "1.0.0/list-isolation-history", label: "List isolation history", className: "api-method get" },
        { type: "doc", id: "1.0.0/delete-isolation-history", label: "Delete isolation history", className: "api-method delete" },
      ],
    },
    {
      type: "category",
      label: "Sound Effects",
      collapsed: true,
      items: [
        { type: "doc", id: "1.0.0/list-sfx-models", label: "List sound effects models", className: "api-method get" },
        { type: "doc", id: "1.0.0/convert-sound-effect", label: "Create sound effect", className: "api-method post" },
      ],
    },
    {
      type: "category",
      label: "Dubbing",
      collapsed: true,
      items: [
        { type: "doc", id: "1.0.0/list-dubbing-models", label: "List dubbing models", className: "api-method get" },
        { type: "doc", id: "1.0.0/create-dubbing-project", label: "Create dubbing project", className: "api-method post" },
        { type: "doc", id: "1.0.0/list-dubbing-projects", label: "List dubbing projects", className: "api-method get" },
        { type: "doc", id: "1.0.0/get-dubbing-project", label: "Get dubbing project", className: "api-method get" },
        { type: "doc", id: "1.0.0/delete-dubbing-project", label: "Delete dubbing project", className: "api-method delete" },
        { type: "doc", id: "1.0.0/create-dubbing-language", label: "Create language target", className: "api-method post" },
        { type: "doc", id: "1.0.0/list-dubbing-languages", label: "List language targets", className: "api-method get" },
        { type: "doc", id: "1.0.0/get-dubbing-language", label: "Get language target", className: "api-method get" },
        { type: "doc", id: "1.0.0/delete-dubbing-language", label: "Delete language target", className: "api-method delete" },
        { type: "doc", id: "1.0.0/get-dubbing-source-transcript", label: "Get source transcript", className: "api-method get" },
        { type: "doc", id: "1.0.0/add-dubbing-source-segment", label: "Add source segment", className: "api-method post" },
        { type: "doc", id: "1.0.0/update-dubbing-source-segment", label: "Update source segment", className: "api-method patch" },
        { type: "doc", id: "1.0.0/delete-dubbing-source-segment", label: "Delete source segment", className: "api-method delete" },
        { type: "doc", id: "1.0.0/batch-update-dubbing-source-segments", label: "Batch update source segments", className: "api-method patch" },
        { type: "doc", id: "1.0.0/get-dubbing-target-transcript", label: "Get target transcript", className: "api-method get" },
        { type: "doc", id: "1.0.0/update-dubbing-target-segment", label: "Update target segment", className: "api-method patch" },
        { type: "doc", id: "1.0.0/batch-update-dubbing-target-segments", label: "Batch update target segments", className: "api-method patch" },
        { type: "doc", id: "1.0.0/regenerate-dubbing-target", label: "Regenerate target", className: "api-method post" },
      ],
    },
    {
      type: "category",
      label: "Forced Alignment",
      collapsed: true,
      items: [
        { type: "doc", id: "1.0.0/list-alignment-models", label: "List forced alignment models", className: "api-method get" },
        { type: "doc", id: "1.0.0/create-forced-alignment", label: "Create forced alignment", className: "api-method post" },
      ],
    },
  ],
};

export default sidebar.apisidebar;